name: .NET Core

on:
  push:
    branches:
      - main
    paths:
      - 'TailwindTraders.Website/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.3    

    - name: Install dependencies
      run: dotnet restore ./Source/*.sln
   
    - name: Build
      run: dotnet build ./Source/*.sln --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish ./Source/Tailwind.Traders.Web/Tailwind.Traders.Web.csproj -c Release -o './staging'
   
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_2 }}

    - name: Run Azure webapp deploy action
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.WEBAPP_APPSERVICE_NAME_STAGING }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING  }}
        package: TailwindTraders.Website/Source/Tailwind.Traders.Web/publish
        
    - name: Azure logout
      run: |
        az logout
